defaults:
  -
    # default layout for all pages
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

plugins:
  - jekyll-optional-front-matter # Markdown files to not require front matter

# jekyll-optional-front-matter
optional_front_matter:
  remove_originals: true

# Order of these matter!
# (For example: `home_sections` uses `quotes`, therefore `quotes` is positioned
# before `home_sections`.)
collections:
  quotes:
  home_sections:
    order:
      - quando-chiedere-aiuto.md
      - sintomo.md
      - trattamento.md
  aree-di-intervento_sections:
    order:
      - disturbi-di-ansia.md
      - disturbi-dell-umore.md
      - disturbi-alimentari.md
      - disturbi-di-personalita.md
      - disturbi-somatoformi.md
      - dipendenze-patologiche.md
      - disagi-dell-infanzia-e-dell-adolescenza.md
      - problemi-di-relazione.md
      - disfunzioni-della-sfera-sessuale.md
