defaults:
  -
    # default layout for all pages
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

plugins:
  - jekyll-optional-front-matter # Markdown files to not require front matter
  - jekyll-postcss

# jekyll-optional-front-matter
optional_front_matter:
  remove_originals: true
