#!/usr/bin/env bash

set -euo pipefail
trap "echo 'error: Script failed: see failed command above'" ERR

cd "$(dirname "$0")/.."

bundle exec jekyll serve --livereload
# JEKYLL_ENV=production bundle exec jekyll build
