on:
  push:
    branches: main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - uses: actions/setup-node@v2
      #   with:
      #     node-version: '14'
      - uses: ruby/setup-ruby@v1
        with:
          # ruby-version: 2.6 # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Run bunch of commands
        run: |
          set -x
          # ls -A
          npm install
          git clean -ndx
          # bundle install
          # ls -A
          # git status --short
          # git branch --verbose --verbose
          # git diff
          # git checkout --orphan gh-pages
          # git branch --verbose --verbose
          # git status --short
          JEKYLL_ENV=production bundle exec jekyll build
          git clean -ndx
          git status --short
          tree docs/
