on:
  push:
    branches: main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - uses: actions/setup-node@v2
      #   with:
      #     node-version: '14'
      - uses: ruby/setup-ruby@v1
        with:
          # ruby-version: 2.6 # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Run bunch of commands
        env:
          FOO: ${{ toJson(pusher) }}
        run: |
          set -x
          echo "$FOO"
          npm install
          JEKYLL_ENV=production bundle exec jekyll build
          NODE_ENV=production npx postcss styles.css --output docs/styles.css
          git checkout --orphan gh-pages
          git add .bundle/config  # because following `git rm --cached` would fail otherwise
          git rm -r --cached -- .
          git add --force docs/
          git status --short
          git commit --message="Publishing $(git rev-parse --short main) on $(date)"
          git push --force origin gh-pages
