on:
  push:
    branches: main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          # ruby-version: 2.6 # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Run bunch of commands
        run: |
          ls -A
          npm install
          bundle install
          ls -A
          git checkout --orphan gh-pages
          git branch --verbose --verbose
          git status --short
