on:
  push:
    branches: main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        run: |
          ls -A
          npm install
          bundle install
          ls -A
          git checkout --orphan gh-pages
          git branch --verbose --verbose
          git status --short
